### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [hessnd/project7#1]
There are a few things I'd like fixed here:

- Change "Date" label to "Day", since that's more accurate.
- Format the results nicely, just like in the previous project, rather than just spitting out a hash.
- When I enter a month, but not a day, I get no results, where I would expect to get all the results for that month. [This resource](http://www.w3schools.com/tags/att_input_required.asp) may help you implement a simple solution to this if you intend for the user to fill out every field.
- When I submit the form, I expect to see my changes saved in the form, as specified in the project (`every form field should always show the current parameters`). You can do [something like this](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) to make sure the current params are reflected in the form.

Let me know when you've updated this and I'll take another look.

**Comment by hessnd** [comment]
I'm pretty sure I fixed everything you said.  I have one issue with the ruby if and else statements, in my index file I have it setup up with if @holiday_search.any? but it doesn't display whats in my else statement when there aren't any holidays.

**Comment by chrisvfritz** [comment]
This is looking much better! I believe we were able to resolve the if else statements problem in class, but let me know if you still have questions about it. Two more small things I'd like fixed though:

It looks like each holiday is listed not only in its own `<li>`, but also its own `<ul>`, like this:

``` html
<ul>
  <li>2015-01-01 New Year's Day</li>
</ul>
<ul>
  <li>2015-01-01 Last Day of Kwanzaa</li>
</ul>
```

On days when there are multiple holidays, like January 1st, could you instead list all the holidays in a single `<ul>`. That makes more sense to me, since they're all part of the same list. See below for an example.

``` html
<ul>
  <li>2015-01-01 New Year's Day</li>
  <li>2015-01-01 Last Day of Kwanzaa</li>
</ul>
```

The other thing that isn't working quite right is that the country field is resetting to US every time I submit, instead of retaining its value.

Let me know when these two are fixed and I'll take another look. And don't hesitate to let me know if you had any questions.

**Comment by hessnd** [comment]
I have fixed the issue with the unordered lists but i'm having an issue with the country field.  If I search in the US it works fine but if I change the country code I keep getting an error.

**Comment by hessnd** [comment]
Nevermind I think I got it, I tested some example country codes from the holiday api website and they worked fine.

**Comment by chrisvfritz** [comment]
Uh oh - you may already be on your way to fixing this, but it looks like visiting the site for the first time (without parameters from a form) now immediately results in an `Internal Server Error`. When I test the app locally, it looks like the culprit is an exception thrown by an empty country parameter being passed to the API.

**Comment by hessnd** [comment]
Shoot, I thought I had fixed that.  Is there a way to pass an initial country value as US until someone changes the country?

**Comment by chrisvfritz** [comment]
You can assign a default to the parameter before making the API call with something like this is Ruby:

params['country'] ||= 'us'

That makes the country 'us' *only* if there isn't already a value in params['country']. Does that make sense?

**Comment by hessnd** [comment]
Yea it does, I just edited the code in my app.rb file and will upload it now

**Comment by chrisvfritz** [comment]
:+1: Looks good!
